### ISSUE TITLE
Look at timeout of 5000ms exceeded in the XMLHttpRequest/

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#121]
Many timeout 
Look at https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout

About
Error
{
  "message": "timeout of 5000ms exceeded",
  "name": "Error",
  "stack": "Error: timeout of 5000ms exceeded\n    at e.exports (http://10.240.4.179/static/js/1.478ff19e.chunk.js:1:6477)\n    at XMLHttpRequest.l.ontimeout (http://10.240.4.179/static/js/1.478ff19e.chunk.js:1:5597)",
  "config": {
    "url": "/proxy-githubusercontent/jdh-observer/jdh001-JJszM3GwAYDs/main/namelesscrowd/The-Nameless-Crowd_anon_V3.ipynb",
    "method": "get",
    "headers": {
      "Accept": "application/json, text/plain, */*"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": "5000",
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1
  },
  "code": "ECONNABORTED"
}

**Comment by eliselavy** [comment]
put  REACT_APP_API_TIMEOUT=60000
