### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'layer')

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#438]
Error:

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'layer')
    at ArticleLayer.js:293:48
    at Array.map (<anonymous>)
    at J (ArticleLayer.js:291:25)
    at oa (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at ju (react-dom.production.min.js:250:347)
    at _u (react-dom.production.min.js:250:278)
    at Su (react-dom.production.min.js:250:138)
    at mu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
```

```
 {paragraphsGroups.map((paragraphsIndices, i) => {
        const firstCellInGroup = paragraphs[paragraphsIndices[0]]
        const isPlaceholder = firstCellInGroup.layer !== layer
        if (isPlaceholder) {
          return (
```

Notebook

https://github.com/jdh-observer/jdh001-MyifnvNPDgUx/blob/main/taking-the-measure-of-social-democracy.ipynb

Prod

https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZqZGgwMDEtTXlpZm52TlBEZ1V4JTJGMTUyODA4OWFhN2FjMDFiMTI0ZTJhNzU5ZjZiM2U2YzlmNzcyOWViYSUyRnRha2luZy10aGUtbWVhc3VyZS1vZi1zb2NpYWwtZGVtb2NyYWN5LmlweW5i

Dev
http://10.240.4.179/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZqZGgwMDEtTXlpZm52TlBEZ1V4JTJGbWFpbiUyRnRha2luZy10aGUtbWVhc3VyZS1vZi1zb2NpYWwtZGVtb2NyYWN5LmlweW5i

**Comment by eliselavy** [comment]
SOLVED by removing cell

  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "tags": [
     "hidden"
    ]
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "               _                           \n",
       "platform       x86_64-pc-linux-gnu         \n",
       "arch           x86_64                      \n",
       "os             linux-gnu                   \n",
       "system         x86_64, linux-gnu           \n",
       "status                                     \n",
       "major          3                           \n",
       "minor          6.3                         \n",
       "year           2020                        \n",
       "month          02                          \n",
       "day            29                          \n",
       "svn rev        77875                       \n",
       "language       R                           \n",
       "version.string R version 3.6.3 (2020-02-29)\n",
       "nickname       Holding the Windsock        "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "R.version"
   ]
  },

**Comment by eliselavy** [comment]
if text before ok
<img width="862" alt="Screenshot 2022-05-10 at 13 21 04" src="https://user-images.githubusercontent.com/35602279/167617444-4cbc2e88-64a5-461f-b74d-6da7a34355e2.png">

**Comment by salaun-marion** [comment]
Cell has been removed : https://journalofdigitalhistory.org/en/article/MyifnvNPDgUx
